import { computeCondition, STATUS_LABEL } from "./rules";
import { ddmmyyyy, num } from "./format";
import type { CompanyCode, Transaction } from "./types";

export const USBC101_COLUMNS = [
  "NO #",
  "DATE",
  "TYPE",
  "MA SKU",
  "DECRIPTION",
  "Cust. Name/ Check No",
  "CONTACT",
  "EXPENSE/ Purchase/ Trade In",
  "CONDITION Return/PO",
  "CONDITION RECEIPT",
  "CONDITION DEPOSIT",
  "CASH",
  "BANKWIRE",
  "ZELLE",
  "CHECK",
  "SO#",
  "Root Appt ID",
  "JM US RECEIPT N#",
  "SOURCE 1",
  "SOURCE 2",
  "SALE US",
  "SALE ONLINE",
  "% SUPPORT",
  "TRANSACTION VALUE",
];

export const RC_JM_COLUMNS_PC49 = [
  "NO #",
  "DATE",
  "DECRIPTION",
  "Cust. Name/ Check No",
  "EXPENSE/ Purchase/ Trade In",
  "RECEIPT",
  "DEPOSIT",
  "RECEIPT #",
  "SOURCE 1",
  "SOURCE 2",
  "SALE #1",
  "TỶ LỆ %",
  "SALE #2",
  "TỶ LỆ %",
  "SALE ONLINE",
  "% SUPPORT",
  "TRANSACTION VALUE",
  "RUNG CHUONG",
  "STATUS",
];

export const RC_JM_COLUMNS_TRANS = [
  "NO #",
  "DATE",
  "DECRIPTION",
  "SO#",
  "Cust. Name/ Check No",
  "EXPENSE/ Purchase/ Trade In",
  "RECEIPT",
  "DEPOSIT",
  "JM US RECEIPT N#",
  "OLD RECEIPT NUMBER",
  "SOURCE 1",
  "SOURCE 2",
  "SALE #1",
  "TỶ LỆ %",
  "SALE #2",
  "TỶ LỆ %",
  "SALE #3",
  "TỶ LỆ %",
  "SALE ONLINE #1",
  "SALE ONLINE #2",
  "SALE ONLINE #3",
  "% SUPPORT",
  "TRANSACTION VALUE",
  "DEPOSIT DATE",
  "CONTACT",
  "SKU",
  "STATUS",
];

export function rcJmHeaders(company: CompanyCode | "all") {
  return company === "Trans" ? RC_JM_COLUMNS_TRANS : RC_JM_COLUMNS_PC49;
}

const pctCell = (v?: number) => (v != null && v !== 0 ? `${v}%` : "");

export function rcJmCells(t: Transaction, index: number, company: CompanyCode | "all") {
  const c = computeCondition(t);
  const base = {
    no: index + 1,
    date: ddmmyyyy(t.ngay),
    desc: t.dienGiai,
    customer: t.khach,
    expense: c.returnPo ? num(c.returnPo) : "",
    receipt: c.receipt ? num(c.receipt) : "",
    deposit: c.deposit ? num(c.deposit) : "",
    rc: t.rcJmNo || "",
    source1: t.source1 || "",
    source2: t.source2 || "",
    sale1: t.sale1 || "",
    sale2: t.sale2 || "",
    sale3: t.sale3 || "",
    sale1Pct: pctCell(t.sale1Pct),
    sale2Pct: pctCell(t.sale2Pct),
    sale3Pct: pctCell(t.sale3Pct),
    saleOnline: t.saleOnline || "",
    saleOnline2: t.saleOnline2 || "",
    saleOnline3: t.saleOnline3 || "",
    value: t.transactionValue || "",
    pct: t.pctSupport ?? "",       // % SUPPORT — KHÁC tỷ lệ phân bổ
    status: STATUS_LABEL[t.trangThai],
  };

  if (company === "Trans") {
    return [
      base.no,
      base.date,
      base.desc,
      t.soNo || "",
      base.customer,
      base.expense,
      base.receipt,
      base.deposit,
      base.rc,
      t.oldReceiptNo || "",
      base.source1,
      base.source2,
      base.sale1,
      base.sale1Pct,
      base.sale2,
      base.sale2Pct,
      base.sale3,
      base.sale3Pct,
      base.saleOnline,
      base.saleOnline2,
      base.saleOnline3,
      base.pct,
      base.value,
      t.depositDate ? ddmmyyyy(t.depositDate) : "",
      t.contact || "",
      t.maSku || "",
      base.status,
    ];
  }

  return [
    base.no,
    base.date,
    base.desc,
    base.customer,
    base.expense,
    base.receipt,
    base.deposit,
    base.rc,
    base.source1,
    base.source2,
    base.sale1,
    base.sale1Pct,
    base.sale2,
    base.sale2Pct,
    base.saleOnline,
    base.pct,
    base.value,
    t.bellCode || "",
    base.status,
  ];
}
